version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.0-node-browsers
        environment:
          BUNDLE_PATH: .bundle
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          working_directory: arelable
          command: |
            bin/setup
      - save_cache:
          paths:
            - .bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: Run RSpec
          working_directory: arelable
          command: bin/rspec
      - store_test_results:
          path: /tmp/test-results
